# please note that docker-compose isn't working on trusty with pip3 (trusty python3-six package is too old)
dist: trusty
git:
  quiet: true
  depth: 1
notifications:
  email: false
language: java
jdk: openjdk8
python: 3
addons:
  apt:
    update: true
    packages:
      - jq
      - bash
      - python3-pip
install: true
before_install:
  - which pip3    || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip # not pip3
  - which pip3    || echo 'which pip3 command failed.'
  - pip3 install --user $(whoami) --upgrade httpie
  - http --version --debug
script:
  - http https://httpbin.org/get | jq '.'
  - http https://httpbin.org/get
cache:
  packages: true
  pip: true
