dist: trusty
git:
  quiet: true
  depth: 1
notifications:
  email: false
language: java
jdk: openjdk8
python: 3
service:
  - docker
addons:
  apt:
    update: true
    packages:
      - bash
      - docker-ce
      - python3-pip
install: true
before_install:
  - docker-compose -v
  - which pip3    || echo 'which pip3 command failed.'
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip # not pip3
  - which pip3    || echo 'which pip3 command failed.'
  - pip3 install --user $(whoami) --upgrade docker-compose httpie >/dev/null 2>&1
  - http --version --debug
  - docker-compose -v
script:
  - docker pull kennethreitz/httpbin
  - docker run --rm --name httpbin -d -p 80:80 kennethreitz/httpbin
  - http :80/get | jq '.'
  - http :80/get
after_script:
 #- docker rm -f -v httpbin
  - docker stop httpbin
cache:
  packages: true
  pip: true
  directories:
    - ~/.docker
